version: '3.3'

services:
  juneogo:
    image: ghcr.io/staketab/juneo-docker/socorta:1.0.0
    container_name: juneo
    restart: unless-stopped
    ports:
      - "9650:9650"
      - "9651:9651"
    volumes:
      - /root/juneogo:/root/juneogo
      - /root/juneogo/plugins:/root/juneogo/plugins
    command:
      [
        "/usr/bin/juneogo",
        "--http-host=0.0.0.0",
        "--http-port=9650"
      ]
    networks:
      - juneo

networks: 
  juneo:
    driver: bridge
