version: '3.3'

services:
  juneogo:
    image: ghcr.io/staketab/juneo-docker/socorta:1.0.0
    container_name: juneo
    restart: always
    ports:
      - "9650:9650"
      - "9651:9651"
    volumes:
      - /root/.juneogo:/root/.juneogo
    command: ["/juneogo-binaries/juneogo", "--http-host", "0.0.0.0", "--http-port", "9650"]
    networks:
      - juneo

networks: 
  juneo:
    driver: bridge
